# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fc9d1c065cdc01bce5fac2049099c8b6c8cb95410ccbcabf1f0c3a13ec7d272a67b4ebe68a290af801cb00c137d77c1442fa3a19ccfa9fdca758d3325885427

test:
  secret_key_base: b74fdc5f554296791a27f02d773e371d33d608f9a3972713c0167c0d4ff4dbac7579b3b3b547d8b41f5ed19e28bf0953e3c5b65a386058b61bbc2eda481001b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
